# spring:
#   datasource:
#     url: jdbc:h2:mem:veterinaria;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#     driverClassName: org.h2.Driver
#     username: sa
#     password:
#   jpa:
#     hibernate:
#       ddl-auto: create-drop
#     show-sql: true
#   h2:
#     console:
#       enabled: true
#       path: /h2-console

#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: tu_correo@gmail.com
#     password: tu_password
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true

# logging:
#   level:
#     org.hibernate.SQL: DEBUG
