version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: vetclinic_mysql 
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '7885:3306'
    volumes:
      
      - mysql_data:/var/lib/mysql 
      
volumes:
  mysql_data: